### ISSUE TITLE
Pr

### ISSUE THREAD

**Issue by short-matthew-f** [jcjordn5/project1#5]
README: Nice readme, thanks for being detailed!

HTML: Well organized, nice use of fonts, stylesheets, classes and ids.

CSS: You have a few media queries, I'm excited for that.  Lots of things that are tied to IDs could probably be tied to classes:

``` CSS
#score1 {
  position:absolute;
  margin-left: -20%;
  margin-top: 40px;
  font-size: 28px;
}
#score2{
  position: absolute;
  margin-top: 40px;
  margin-left: 120%;
  font-size: 28px;
}
```

vs.

``` CSS
.score-card {
  position:absolute;
  margin-top: 40px;
  font-size: 28px;
}

#score1 { margin-left: -20%; }

#score2{ margin-left: 120%; }
```

JavaScript: The real loss here is just with the immense number of things which are hard coded, and your need to bind and unbind methods as you go.  You can kill and re-render the page, if you have listeners up near the top of the DOM.

Overall: Good job, it works, and works well.  

Next Time: Keep on working on thinking programmatically.
